name: James W Brown
favicon: null
layout_spectrum: 1
typography_spectrum: 0.49833
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b5b7b6'
    - '#626765'
    - '#60de2a'
    - '#aeed8f'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.6875
  rhythmicContrast: 1
purpose: []
