name: James W Brown
favicon: null
layout_spectrum: 1
typography_spectrum: 0.49833
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#3f4342'
    - '#5ade23'
    - '#9a9c9c'
    - '#cacbcb'
  brandStrength: 0.625
  lightness: 0.5625
  saturation: 0.6875
  rhythmicContrast: 1
purpose: []
